_.title  # unused attribute (src/visualize/main.py:27)
_.data  # unused attribute (src/visualize/panel_word_frequencies.py:102)
_.formatter  # unused attribute (src/visualize/panel_word_trends.py:63)
_.visible  # unused attribute (src/visualize/panel_word_trends.py:114)
_.items  # unused attribute (src/visualize/panel_word_trends.py:117)
_.data  # unused attribute (src/visualize/panel_word_trends.py:119)
on_server_loaded  # unused function (src/visualize/server_lifecycle.py:22)
